dentist_booking/booking/urls.py
from django.contrib.auth import logout
from django.urls import path

from booking.views import IndexView, BookingView, get_schedule

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('book/', BookingView.as_view(), name='booking'),
    path('get-schedule/', get_schedule, name='get_schedule'),
]

dentist_booking/dentist_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.api.urls', namespace='users')),
    path('booking/', include('booking.api.urls', namespace='booking')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dentist_booking/users/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.views import SignUpView, activate, SignInView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    # path('signin', auth_views.LoginView.as_view(template_name='users/signin.html')),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
]

dentist_booking/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Dentist booking</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'booking:index' %}">Home <span class="sr-only">Aboba</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'booking:booking' %}">Booking</a>
            </li>
            {% if request.user.is_staff %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Admin panel
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/admin/booking/appointment/" target="_blank">Appointments</a>
                    <a class="dropdown-item" href="/admin/booking/procedure/" target="_blank">Procedures</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/admin/booking/schedule/" target="_blank">Schedules</a>
                </div>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            {% if request.user.is_authenticated %}
            <span>Hi, {{ request.user.first_name }}!</span>
            <a href="{% url 'users:logout' %}" class="btn btn-light">Log out
                <span class="bi bi-box-arrow-right"></span>
            </a>
            {% else %}
            <a class="btn btn-light" href="{% url 'users:signup' %}">Sign up</a> /
            <a class="btn btn-light" href="{% url 'users:signin' %}">Login</a>
            {% endif %}
        </form>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

dentist_booking/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="mask d-flex align-items-center h-100 gradient-custom-3 m-5">
    <div class="container h-100 " style="text-align: center;margin-top: 5rem;">
        <h1 class="display-4" style="font-style: italic;">Welcome to dentist booking application!</h1>
        <h1 class="display-1" style="text-transform: uppercase !important;">It's Nice To Meet You</h1>
    </div>
</div>
{% endblock %}