dentist_booking/dentist_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.api.urls', namespace='users')),
    path('booking/', include('booking.api.urls', namespace='booking')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dentist_booking/users/api/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.api.views.account_activation import activate
from users.api.views.sign_in import SignInView
from users.api.views.sign_up import SignUpView


app_name = 'users'
urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
]

dentist_booking/users/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.views import SignUpView, activate, SignInView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    # path('signin', auth_views.LoginView.as_view(template_name='users/signin.html')),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
]

dentist_booking/users/models.py
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    phone = PhoneNumberField(null=False, blank=False, unique=True)

    def __str__(self):
        return self.get_full_name()

dentist_booking/users/models/user.py
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    phone = PhoneNumberField(null=False, blank=False, unique=True)

    def __str__(self):
        return self.get_full_name()

dentist_booking/users/api/forms/login.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Username',
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'})
    )

dentist_booking/users/api/forms/registration.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from users.models import User


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        label='First name',
        max_length=30,
        required=True,
        help_text='Enter your first name',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    last_name = forms.CharField(
        label='Last name',
        max_length=30,
        required=True,
        help_text='Enter your last name',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    username = forms.CharField(
        label='Username',
        max_length=30,
        required=True,
        help_text='Enter your username',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    email = forms.EmailField(
        label='Email',
        max_length=30,
        required=True,
        help_text='Enter your email',
        widget=forms.EmailInput(attrs={'class': 'form-control form-control-lg'})
    )
    phone = forms.CharField(
        label='Phone number',
        required=True,
        help_text='Enter your prone number',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    password1 = forms.CharField(
        label='Password',
        required=True,
        help_text='Enter your password',
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'})
    )
    password2 = forms.CharField(
        label='Confirm password',
        required=True,
        help_text='Confirm your password',
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'})
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'phone', 'password1', 'password2')

dentist_booking/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        label='First name',
        max_length=30,
        required=True,
        help_text='Enter your first name',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    last_name = forms.CharField(
        label='Last name',
        max_length=30,
        required=True,
        help_text='Enter your last name',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    username = forms.CharField(
        label='Username',
        max_length=30,
        required=True,
        help_text='Enter your username',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    email = forms.EmailField(
        label='Email',
        max_length=30,
        required=True,
        help_text='Enter your email',
        widget=forms.EmailInput(attrs={'class': 'form-control form-control-lg'})
    )
    phone = forms.CharField(
        label='Phone number',
        required=True,
        help_text='Enter your prone number',
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    password1 = forms.CharField(
        label='Password',
        required=True,
        help_text='Enter your password',
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'})
    )
    password2 = forms.CharField(
        label='Confirm password',
        required=True,
        help_text='Confirm your password',
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'})
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'phone', 'password1', 'password2')


class SignInForm(AuthenticationForm):
    username = forms.CharField(
        label='Username',
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'})
    )
    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'})
    )

dentist_booking/users/api/views/account_activation.py
from django.contrib.auth import login
from django.http import HttpResponse
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode

from users.models import User
from users.tokens import account_activation_token


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

dentist_booking/users/api/views/sign_in.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

from users.api.forms.login import LoginForm


class SignInView(LoginView):
    form_class = LoginForm
    template_name = 'users/signin.html'

    def get_success_url(self):
        return reverse_lazy('booking:index')

dentist_booking/users/api/views/sign_up.py
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View

from users.api.forms.registration import RegistrationForm
from users.tokens import account_activation_token


class SignUpView(View):
    form_class = RegistrationForm
    template_name = 'users/signup.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('booking:index')
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('users/acc_activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')

        return render(request, self.template_name, {'form': form})

dentist_booking/users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.views.generic import View

from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from users.forms import SignUpForm, SignInForm
from users.models import User
from users.tokens import account_activation_token


class SignUpView(View):
    form_class = SignUpForm
    template_name = 'users/signup.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('users/acc_activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')

        return render(request, self.template_name, {'form': form})


class SignInView(LoginView):
    form_class = SignInForm
    template_name = 'users/signin.html'

    def get_success_url(self):
        return reverse_lazy('booking')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

dentist_booking/templates/users/acc_activate_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

dentist_booking/templates/users/signin.html
{% extends 'base.html' %}
{% block content %}
<div class="mask d-flex align-items-center h-100 gradient-custom-3 m-5">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-5">
                        <h2 class="text-uppercase text-center mb-5">Welcome back!</h2>
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="form-outline mb-4">
                                {{ field }}
                                <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% if field.help_text %}
                                <small style="display: none">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endfor %}
                            <div class="d-flex justify-content-center">
                                <button type="submit"
                                        class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">
                                    Sign In
                                </button>
                            </div>
                            {% if form.errors %}
                            <div class="alert alert-danger mt-4" role="alert">
                                Your username and password didn't match. Please try again.
                            </div>
                            {% endif %}
                            <p class="text-center text-muted mt-5 mb-0">Don't have an account?
                                <a href="{% url 'users:signup' %}" class="fw-bold text-body">
                                    <u>Register here</u>
                                </a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dentist_booking/templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="mask d-flex align-items-center h-100 gradient-custom-3 m-5">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-5">
                        <h2 class="text-uppercase text-center mb-5">Create an account</h2>
                        <form method="post">
                            {% csrf_token %}

                            {% for field in form %}
                            <div class="form-outline mb-4">
                                {{ field }}
                                <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% if field.help_text %}
                                <small style="display: none">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endfor %}
                            <div class="d-flex justify-content-center m-4">
                                <button type="submit"
                                        class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">
                                    Register
                                </button>
                            </div>
                            <p class="text-center text-muted mt-5 mb-0">Have already an account?
                                <a href="{% url 'users:signin' %}" class="fw-bold text-body">
                                    <u>Login here</u>
                                </a>
                            </p>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}